-- base de datos
DROP DATABASE IF EXISTS usuarios;

CREATE DATABASE IF NOT EXISTS usuarios;

USE usuarios;

CREATE TABLE usuario(

id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
clave VARCHAR(10) NOT NULL,
nombre VARCHAR(40) NOT NULL,
correo VARCHAR(100) NOT NULL,
ciudad VARCHAR(100) NOT NULL,
);